modLoader="kotlinfml"
loaderVersion="${loaderVersion}"
issueTrackerURL="https://github.com/sargunv/level-up-hp/issues"
logoFile="leveluphp_logo.png"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="Level Up HP"
#updateJSONURL=""
displayURL="https://minecraft.curseforge.com/projects/level-up-hp"
credits=""
authors="Sargun Vohra"
description='''
Gain hearts of health by killing mobs or consuming heart containers.
'''

[["dependencies.${modId}"]]
    modId="forge"
    mandatory=true
    versionRange="${forgeAcceptedVersion}"
    ordering="NONE"
    side="BOTH"

[["dependencies.${modId}"]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion}]"
    ordering="NONE"
    side="BOTH"
