version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle.kts" }}
    - run: ./gradlew setupCiWorkspace check build
    - store_artifacts:
        path: build/libs
        destination: jars
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle.kts" }}
